pt

diff --git a/games/source/Dockerfile b/games/source/Dockerfile
--- a/games/source/Dockerfile
+++ b/games/source/Dockerfile
@@ -31,10 +31,24 @@ ENV         DEBIAN_FRONTEND=noninteractive
 
 # Install required packages
 RUN apt-get update && \
-	apt-get install -y wget build-essential  gawk bison python3.4
+	apt-get install -y wget build-essential gawk bison
 
-# Check if we have the correct version of python
-RUN python --version
+RUN apt-get update \
+	&& apt-get install -y --no-install-recommends \
+	python3.4 \
+	python3.4-dev \
+	python3.4-venv \
+	git \
+	&& apt-get clean \
+	&& rm -rf /var/lib/apt/lists/*
+
+RUN if command -v python3.4 >/dev/null 2>&1; then \
+	ln -s $(command -v python3.4) /usr/local/bin/python; \
+	else \
+	echo "Python 3.4 not found."; \
+	exit 1; \
+	fi
+
 
 # Make an alias for python3.4 to python
 # RUN ln -s /usr/bin/python3.4 /usr/bin/python
